name       : librepo
version    : 1.9.1
release    : 3
source     :
    - https://github.com/rpm-software-management/librepo/archive/1.9.1.tar.gz : 32c428cb3322f3c54f1c8cf5af9350d33bb5fecc0aced5e54ef05a51eb2c5c2f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Repodata downloading library
description: |
    A library providing C and Python (libcURL like) API to
    downloading repository metadata.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(glib-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(openssl)
    - pkgconfig(python3)
    - attr-devel
    - gpgme-devel
    - libassuan-devel
setup      : |
    %cmake -DPYTHON_DESIRED:str=3
build      : |
    %make
install    : |
    %make_install
