name       : librepo
version    : 1.8.1
release    : 1
source     :
    - https://github.com/rpm-software-management/librepo/archive/1.8.1/librepo-1.8.1.tar.gz : 9e15caff6eb9301f53be8a0d9164063ebe9cd6db382d8725d9af6cf363050d5f
license    : LGPL-2.1
component  : programming.library
summary    : Repodata downloading library
description: |
    A library providing C and Python (libcURL like) API to
    downloading repository metadata.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(expat)
    - pkgconfig(glib-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(openssl)
    - pkgconfig(python3)
    - attr-devel
    - gpgme-devel
    - libassuan-devel
setup      : |
    %cmake -DPYTHON_DESIRED:str=3
build      : |
    %make
install    : |
    %make_install
